services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn keep_alive:app & python main.py"
    envVars:
      - key: API_URL
        value: ${API_URL}
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: CHANNEL_ID
        value: ${CHANNEL_ID}
      - key: PORT
        value: 8080
